pipeline {
  agent {
    docker { 
      image 'node:16-alpine'
      args '-u root' // Add this line to run commands as root user
    }
  }
  stages {
    stage('Test') {
      steps {
        script {
          // Add 'npm install' command here if needed
          sh 'node --version'
        }
      }
    }
  }
}

